# $language = "python"
# $interface = "1.0"
def main():
    crt.Screen.Send("cd /bossapp1/prg/bin\r")
    crt.Screen.WaitForString("t-as-js:/bossapp1/prg/bin$")
    crt.Screen.Send("kill `ps -ef|grep DA_IM_Bank_Recon |grep -v log|awk '{print $2}'`\r")
    crt.Screen.WaitForString("t-as-js:/bossapp1/prg/bin$")
    crt.Screen.Send("telnet 10.1.0.165\r")
    crt.Screen.WaitForString("login:")
    crt.Screen.Send("uig\r")
    crt.Screen.WaitForString("Password:")
    crt.Screen.Send("uig\r")
    crt.Screen.WaitForString("test02:/boss/uig$")
    crt.Screen.Send("cd FileMgtV2\r")
    crt.Screen.WaitForString("test02:/boss/uig/FileMgtV2$")
    crt.Screen.Send("gmake\r")
    crt.Screen.WaitForString("test02:/boss/uig/FileMgtV2$")
    crt.Screen.Send("cd /boss/uig/IntfDaemon\r")
    crt.Screen.WaitForString("test02:/boss/uig/IntfDaemon$")
    crt.Screen.Send("rm DA_IM_Bank_Recon\r")
    crt.Screen.WaitForString("test02:/boss/uig/IntfDaemon$")
    crt.Screen.Send("gmake -f uig_file_imp.mk DA_IM_Bank_Recon\r")
    crt.Screen.WaitForString("test02:/boss/uig/IntfDaemon$")
    crt.Screen.Send("exit\r")
    crt.Screen.WaitForString("t-as-js:/bossapp1/prg/bin$")
    crt.Screen.Send("ftp 10.1.0.165\r")
    crt.Screen.WaitForString("Name (10.1.0.165:bossim1):")
    crt.Screen.Send("uig\r")
    crt.Screen.WaitForString("Password:")
    crt.Screen.Send("uig\r")
    crt.Screen.WaitForString("ftp>")
    crt.Screen.Send("bi\r")
    crt.Screen.WaitForString("ftp>")
    crt.Screen.Send("cd IntfDaemon\r")
    crt.Screen.WaitForString("ftp>")
    crt.Screen.Send("get DA_IM_Bank_Recon\r")
    crt.Screen.WaitForString("ftp>")
    crt.Screen.Send("bye\r")
    crt.Screen.WaitForString("t-as-js:/bossapp1/prg/bin$")
    crt.Screen.Send("DA_IM_Bank_Recon -start 30073009 ../conf/DA_IM_Bank_Recon.cfg\r")
    crt.Screen.WaitForString("t-as-js:/bossapp1/prg/bin$")
main()

      